import localFont from "next/font/local";
import "./globals.css";
import TopNavbar from "@/components/Level2/TopNavbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div>
          <TopNavbar />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
