import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import TopNavbar from "@/components/Level2/TopNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.className}`}>
        <div className="fixed top-0 w-full z-[9999]">
          <TopNavbar />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
